### ISSUE TITLE
Missing androidx support?

### ISSUE THREAD

**Issue by ReneFerrari** [rongi/klaster#4] opened 2018-12-12 22:39 UTC
I am using klaster for the first time and it really is charming to use 🥇 

However I could not fully test it yet, since in my project I am using androidx. The RecyclerView import therefore differs to the one from klaster, which leads to the following issue:

> Type argument is not within its bounds: should be subtype of 'androidx.recyclerview.widget.RecyclerView.ViewHolder'

and

> Cannot access class 'androidx.recyclerview.widget.RecyclerView.Adapter'. Check your module classpath for missing or conflicting dependencies

My code looks like this:

    private fun createAdapter(movies: MutableList<Movie>) = Klaster.withViewHolder<MovieViewHolder>()
            .itemCount { movies.size }
            .viewHolder { _, parent ->
                val view = layoutInflater.inflate(R.layout.vh_movies, parent, false)
                MovieViewHolder(view)
            }
            .bind { position ->
                val movie = movies[position]
                tvTitle.text = movie.title
            }
            .build()

How can i resolve those issues?

**Comment by rongi** [comment] 2018-12-13 01:37
I managed to migrate my another project to AndroidX and make it work with current version of Klaster. https://github.com/rongi/rx-presenter-example.

It wasn't without trouble though. The project was building fine, but Android Studio highlighted Klaster code in red, indicating unexisting error. To fix it I had to manually delete all "build" folders in my project and run "Invalidate Caches/Restart..." command in Android Studio. 

Also, it looks like it's important to add 
```properties
android.enableJetifier=true
android.useAndroidX=true
```
options into the project's "gradle.properties" file for the whole thing to work.

**Comment by ReneFerrari** [comment] 2018-12-14 16:37
Firstly sorry for my late answer and thank you for your quick response.

Secondly, I have tried invalidate caches / restart, looked up if enableJetifier and useAndroidX is set, removed my build and .gradle folder yet - unfortunately - it still does not work. I have also looked at the project which you linked me, compared it to mine, but I could not spot any difference (other than the fact that I use a CustomViewHolder and you are not doing this in your poject).

Anyway the only solution (I think) would be migrating Klaster as a whole to androidX.

**Comment by rongi** [comment] 2018-12-14 16:41
Thank you for your response and feedback! Can you provide me with a minimal project that has this issue?

**Comment by ReneFerrari** [comment] 2018-12-14 17:04
[There you go](https://github.com/rongi/klaster/files/2681065/androidX_issue_mvp.zip)

**Comment by rongi** [comment] 2018-12-14 17:56
Thank you for the minimal project, it was very helpful.

Judging by this `classpath 'com.android.tools.build:gradle:3.2.0-beta05'` you use **Android Studio 3.2.0 beta 5**. I've managed to reproduce the issue one this version of Android Studio. It looks like this issue was fixed in later versions of Android Studio though. I can't reproduce it on **Android Studion 3.2.0** and **Android Studio 3.2.1**. Can you update your Android Studio and tell me if it helped?

**Comment by ReneFerrari** [comment] 2018-12-14 18:19
Yes it works! Thanks a lot! I had not even thought for a second that the Android Studio version could play a role in this. 

Again thank you very much for your help 🎉 🎉 🎉

**Comment by rongi** [comment] 2018-12-14 20:50
Thank you for the report!

**Closed by rongi** 2018-12-14 20:50 UTC
