### ISSUE TITLE
NOT working in androidx

### ISSUE THREAD

**Issue by NurseyitTursunkulov** [rongi/klaster#6] opened 2019-03-14 03:00 UTC
please add support for androidx

**Comment by rongi** [comment] 2019-03-14 07:22
Have you seen this issue https://github.com/rongi/klaster/issues/4 ?

**Comment by NurseyitTursunkulov** [comment] 2019-03-14 07:38
hello , I tryed it but it does not work

>

**Comment by rongi** [comment] 2019-03-14 10:16
Thank you for the report. Have you tried all the stuff from that issue?

- delete build folders
- invalidate cache/restart in AS
- add android.enableJetifier=true and android.useAndroidX=true to gradle.properties
- upgrade Android Studio

If nothing of this helps, can you please provide me with a minimal project that reproduces this issue?

**Comment by rongi** [comment] 2019-04-24 22:20
Closing this for now because not enough data to reproduce. Will reopen if more info is available.

**Closed by rongi** 2019-04-24 22:20 UTC
